repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: local
    hooks:
      - id: cx-secret-detection
        name: Cx Secret Detection
        entry: cx
        description: Run Cx CLI secret detection
        stages:
          - pre-commit
        args:
          - hooks
          - pre-commit
          - secrets-scan
        language: system
        minimum_pre_commit_version: "3.2.0"
